version: '3.8'

services:
  application:
    container_name: application
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./storage/database/schema:/docker-entrypoint-initdb.d