version: '3.8'

services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - ./storage/database/schema:/docker-entrypoint-initdb.d